CREATE TABLE POSTS (
       ID INT PRIMARY KEY AUTO_INCREMENT,
       TEXT TEXT NOT NULL,
       IMAGE BLOB,
       OWNER_UID VARCHAR(128) NOT NULL,
       INSTANT TIMESTAMP NOT NULL
);

ALTER TABLE POSTS
    ADD FOREIGN KEY (OWNER_UID)
        REFERENCES USERS(UID);

CREATE TABLE COMMENTS (
       ID INT PRIMARY KEY AUTO_INCREMENT,
       TEXT TEXT NOT NULL,
       OWNER_UID VARCHAR(128) NOT NULL,
       POST_ID INT NOT NULL,
       INSTANT TIMESTAMP NOT NULL
);

ALTER TABLE COMMENTS
    ADD FOREIGN KEY (OWNER_UID)
        REFERENCES USERS(UID);

ALTER TABLE COMMENTS
    ADD FOREIGN KEY (POST_ID)
        REFERENCES POSTS(ID);

CREATE TABLE COMMENTS_USERS (
    USER_UID VARCHAR(128) NOT NULL,
    COMMENT_ID INT NOT NULL,
    PRIMARY KEY (USER_UID, COMMENT_ID)
);

ALTER TABLE COMMENTS_USERS
    ADD FOREIGN KEY (USER_UID)
        REFERENCES USERS(UID);

ALTER TABLE COMMENTS_USERS
    ADD FOREIGN KEY (COMMENT_ID)
        REFERENCES COMMENTS(ID);